DROP TABLE NOTICE CASCADE CONSTRAINTS;

CREATE TABLE NOTICE (
	NOTICE_NO	NUMBER,
	NOTICE_TITLE	VARCHAR2(30) NOT NULL,
	NOTICE_WRITER	VARCHAR2(15) NOT NULL,
	NOTICE_DATE	DATE DEFAULT SYSDATE,
	NOTICE_CONTENT	VARCHAR2(2000),
	FILE_PATH	VARCHAR2(100),
	CONSTRAINT PK_NOTICENO PRIMARY KEY(NOTICE_NO),
	CONSTRAINT FK_NWRITER FOREIGN KEY (NOTICE_WRITER)
		REFERENCES MEMBER (ID)
);	

INSERT INTO NOTICE VALUES (1, '관리자 공지', 'admin', 
	TO_DATE('2017-01-05', 'RRRR-MM-DD'),
	'공지서비스를 게시합니다.  많이 이용해 주세요.', NULL);
	
INSERT INTO NOTICE VALUES (2, '공지서비스 오픈 환영', 'user11', 
	TO_DATE('2017-01-06', 'RRRR-MM-DD'),
	'드디어 오픈되었군요. 많이 이용하겠습니다.', NULL);

INSERT INTO NOTICE VALUES (3, '공지서비스 이용 안내', 'user22', 
	TO_DATE('2017-02-15', 'RRRR-MM-DD'),
	'공지서비스는 회원만 이용할 수 있습니다. 회원 가입하세요.', NULL);

COMMIT;


