/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-07-25 07:07:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import java.util.*;

public final class myInfoView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/member/../../header.jsp", Long.valueOf(1532430829857L));
    _jspx_dependants.put("/views/member/../../footer.html", Long.valueOf(1532430422975L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"memberError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	Member member = (Member)request.getAttribute("member");

	/* member = null; */
	
	//취미 처리
	String[] hobbies = member.getHobby().split(",");
	String[] checked = new String[9];
	for(String s : hobbies){
		switch(s){
		case "game": checked[0] = "checked"; break;
		case "reading": checked[1] = "checked"; break;
		case "music": checked[2] = "checked"; break;
		case "climb": checked[3] = "checked"; break;
		case "sport": checked[4] = "checked"; break;
		case "art": checked[5] = "checked"; break;
		case "bike": checked[6] = "checked"; break;
		case "walk": checked[7] = "checked"; break;
		case "sleep": checked[8] = "checked"; break;
		}
	}

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내정보 보기</title>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("src=\"/second/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//암호 입력 상자에서 포커스가 사라질 때 암호확인 처리함\r\n");
      out.write("\t\t$(\"#pwd2\").blur(function(){\r\n");
      out.write("\t\t\tconsole.log(\"포커스가 사라짐...\");\r\n");
      out.write("\t\t\tvar pwd1 = $(\"#pwd1\").val();\r\n");
      out.write("\t\t\tvar pwd2 = $(\"#pwd2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pwd1 != pwd2){\r\n");
      out.write("\t\t\t\talert(\"암호와 암호확인이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t$(\"#pwd1\").select();\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

	//jsp 파일 안에는 request, session 객체도 내장되어 있음
	String userName = (String)session.getAttribute("userName");
	String userId = (String)session.getAttribute("userId");

      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#menubar ul li {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t\theight: 35px;\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t\tbackground: orange;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#menubar\r\n");
      out.write("\t\r\n");
      out.write("\thr { clear: both; }\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#loginForm table {\r\n");
      out.write("\t\tbackground : LightSkyBlue;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<h1>second</h1>\r\n");
      out.write("<nav id=\"menubar\">\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"/second/test\">testServlet</a></li>\r\n");
      out.write("\t<li>메뉴1</li>\r\n");
      out.write("\t<li>메뉴1</li>\r\n");
      out.write("\t<li>메뉴1</li>\r\n");
      out.write("\t<li>메뉴1</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<div id=\"loginForm\">\r\n");
 if(userName == null){ 
      out.write("\r\n");
      out.write("<form action=\"/second/login\" method=\"post\">\r\n");
      out.write("<table width=\"250\" height=\"75\" cellspacing=\"0\" \r\n");
      out.write("cellpadding=\"0\">\r\n");
      out.write("<tr><td width=\"200\">\r\n");
      out.write("\t<input type=\"text\" name=\"userid\" id=\"userid\" size=\"15\">\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td width=\"50\" rowspan=\"2\">\r\n");
      out.write("\t<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("\t<input type=\"password\" name=\"userpwd\" size=\"15\">\r\n");
      out.write("   </td></tr>\r\n");
      out.write("<tr><td colspan=\"2\">\r\n");
      out.write("\t<a href=\"views/member/memberEnroll.html\">회원가입</a> &nbsp;\r\n");
      out.write("\t<a href=\"#\">아이디/암호조회</a>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("<table width=\"250\" height=\"75\" cellspacing=\"0\" \r\n");
      out.write("cellpadding=\"0\">\r\n");
      out.write("<tr><td width=\"150\">\r\n");
      out.write("\t");
      out.print( userName );
      out.write(" 님.\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td width=\"100\">\r\n");
      out.write("\t<a href=\"/second/logout\">로그아웃</a>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("<tr><td>\t메일 개 </td> <td>쪽지  개</td></tr>\r\n");
      out.write("<tr><td colspan=\"2\">\r\n");
      out.write("\t<a href=\"/second/myinfo?userid=");
      out.print( userId );
      out.write("\">내 정보보기</a>\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<h1 align=\"center\">");
      out.print( member.getUserId() );
      out.write(" 님의 정보</h1>\r\n");
      out.write("\r\n");
      out.write("<form action=\"/second/mupdate\" method=\"post\">\r\n");
      out.write("<table width=\"600\" align=\"center\" cellspacing=\"5\" \r\n");
      out.write("bgcolor=\"#3399ff\">\r\n");
      out.write("<tr><td>아이디</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"userid\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getUserId() );
      out.write("\" readonly>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>이 름</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"username\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getUserName() );
      out.write("\" readonly>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>암 호</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"password\" name=\"userpwd\" id=\"pwd1\"\r\n");
      out.write("\tvalue=\"");
      out.print( member.getUserPwd() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>암호확인</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"password\" id=\"pwd2\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>성 별</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t");
 if(member.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("\t<input type=\"radio\" name=\"gender\" value=\"M\" checked> 남 &nbsp;\r\n");
      out.write("\t<input type=\"radio\" name=\"gender\" value=\"F\"> 여\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t<input type=\"radio\" name=\"gender\" value=\"M\"> 남 &nbsp;\r\n");
      out.write("\t<input type=\"radio\" name=\"gender\" value=\"F\" checked> 여\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>나 이</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"number\" name=\"age\"\r\n");
      out.write("\tvalue=\"");
      out.print( member.getAge() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>이메일</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"email\" name=\"email\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getEmail() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>전화번호</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"tel\" name=\"phone\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getPhone() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>취 미</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr><td><input type=\"checkbox\" name=\"hobby\" value=\"game\" ");
      out.print( checked[0] );
      out.write("> 게임</td>\r\n");
      out.write("\t<td><input type=\"checkbox\" name=\"hobby\" value=\"reading\" ");
      out.print( checked[1] );
      out.write("> 독서</td>\r\n");
      out.write("\t<td><input type=\"checkbox\" name=\"hobby\" value=\"music\" ");
      out.print( checked[2] );
      out.write("> 음악감상</td></tr>\r\n");
      out.write("\t<tr><td><input type=\"checkbox\" name=\"hobby\" value=\"climb\" ");
      out.print( checked[3] );
      out.write("> 등산</td>\r\n");
      out.write("\t<td><input type=\"checkbox\" name=\"hobby\" value=\"sport\" ");
      out.print( checked[4] );
      out.write("> 운동</td>\r\n");
      out.write("\t<td><input type=\"checkbox\" name=\"hobby\" value=\"art\" ");
      out.print( checked[5] );
      out.write("> 그림그리기</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td><input type=\"checkbox\" name=\"hobby\" value=\"bike\" ");
      out.print( checked[6] );
      out.write("> 자전거타기</td>\r\n");
      out.write("\t<td><input type=\"checkbox\" name=\"hobby\" value=\"walk\" ");
      out.print( checked[7] );
      out.write("> 산책</td>\r\n");
      out.write("\t<td><input type=\"checkbox\" name=\"hobby\" value=\"sleep\" ");
      out.print( checked[8] );
      out.write("> 잠자기</td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>하고싶은말</td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<textarea name=\"etc\" rows=\"3\" cols=\"70\">");
      out.print( member.getEtc() );
      out.write("\r\n");
      out.write("\t</textarea>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수정하기\">\r\n");
      out.write("\t\t&nbsp; &nbsp;\r\n");
      out.write("\t\t<a href=\"/second/mdelete?userid=");
      out.print( member.getUserId() );
      out.write("\">탈퇴하기</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<hr>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tfooter {\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight : 70px;\r\n");
      out.write("\t\tbackground : gray;\r\n");
      out.write("\t\ttext-shadow : 1px 1px 2px white;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<footer>\r\n");
      out.write("\tcopyright@iei.or.kr 2018.07.24 íê¸¸ë<br>\r\n");
      out.write("\ttel : 070-1234-5678, fax : 070-1111-2345\r\n");
      out.write("</footer>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
